version: "3"
networks:
  appnet:
    driver: bridge
services:
  app:
    image: quasar:latest
    build: ./app
    container_name: quasar
    restart: always
    ports:
    - "8080:8080"
    networks:
    - appnet
    environment:
    - SERVER_PORT=8080
    - ROOT_LOGGING_LEVEL=INFO
    - LOGGING_LEVEL=DEBUG
    volumes: []
    # - /tmp:/tmp

## este Tech Challenge no tiene DB
# no es necesario levantar nada mas
# lo dejo por las dudas
# 
#  mongo:
#    image: mongo:4.4.10
#    container_name: mongo
#    restart: always
#    ports:
#    - "27017:27017"
#    networks:
#    - appnet

