micronaut:
  application:
    name: quasar
  server:
    host: ${SERVER_HOST:0.0.0.0}
    port: ${SERVER_PORT:8080}
    cors:
      enabled: true


  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

jackson:
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false
    indentOutput: true


netty:
  default:
    allocator:
      max-order: 3


logger:
  levels:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com:
      quasar: ${LOGGING_LEVEL:INFO}
    io:
      micronaut:
        http:
          server:
            netty:
              RoutingInBoundHandler: ${LOGGING_LEVEL:INFO}
              NettyHttpServer: ${LOGGING_LEVEL:INFO}
          client: ${LOGGING_LEVEL:INFO}