micronaut:
  application:
    name: quasar
  server:
    host: ${SERVER_HOST:0.0.0.0}
    port: ${SERVER_PORT:8080}
    cors:
      enabled: true

netty:
  default:
    allocator:
      max-order: 3


logger:
  levels:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    com:
      quasar: ${LOGGING_LEVEL:INFO}
    io:
      micronaut:
        http:
          server:
            netty:
              RoutingInBoundHandler: ${LOGGING_LEVEL:INFO}
              NettyHttpServer: ${LOGGING_LEVEL:INFO}
          client: ${LOGGING_LEVEL:INFO}